backend:
  name: github
  branch: main 
  repo: lutfi-haslab/lutfiikbalmajid-portofolio

# These lines should *not* be indented
media_folder: "static/img/content" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/content" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: blog
  label: "blog"
  folder: blog
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors" 
      widget: "list"
      fields:
        - { name: name, label: Name, widget: select, options: ["Lutfi Ikbal Majid", "ChatGPT", "Claude"] }
        - { name: title, label: Title, widget: select, options: ["Full Stack Developer", "Your AI Advisor", "Your AI Advisor via nat.dev"] } 
        - { name: url, label: URL, widget: string , default: "https://github.com/lutfi-haslab"} 
        - { name: image_url, label: image_url, widget: select, options: ["https://avatars.githubusercontent.com/u/108409669?v=4", "https://lutfiikbalmajid.netlify.app/img/chatgpt.jpg", "https://lutfiikbalmajid.netlify.app/img/claude.jpeg" ] } 
- name: project
  label: "Project"
  folder: docs/Project
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
- name: knowledge-base
  label: "Knowledge Base"
  folder: "docs/Knowledge Base"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"

- name: linux
  label: "Linux"
  folder: "docs/Knowledge Base/linux"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"

- name: javascript
  label: "Javascript"
  folder: "docs/Knowledge Base/javascript"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"

- name: react-js
  label: "ReactJS"
  folder: "docs/Knowledge Base/react-js"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"

- name: blockchain
  label: "Blockchain"
  folder: "docs/Knowledge Base/blockchain"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"

- name: tensorflow-js
  label: "Tensorflow Node/JS"
  folder: "docs/Knowledge Base/tensorflow-js"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: description, label: Description, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"

media_library:
  name: cloudinary
  config:
    cloud_name: haslab
    api_key: 349757768685858
